### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by viceice** [inspect-js/available-typed-arrays#10]
![image](https://user-images.githubusercontent.com/1798109/126320511-4fb916b9-585a-4634-b24d-f3dfc0330cc5.png)

Fails when imported via `utils` package with webpack v5.

Workaround: User `DefinePlugin` to overwrite `global`

```
        new webpack.DefinePlugin({
            // required by `available-typed-arrays`
            global: 'window.globalThis',
        }),
```

**Comment by ljharb** [comment]
Yes, webpack 5 is broken. See https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1

Closing, since there’s nothing actionable here.
